export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_NAME = 'CHANGE_NAME';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOADING = 'LOADING';

// ADD CONTACT CONSTANTS
export const CHANGE_ADD_CONTACT_EMAIL = 'CHANGE_ADD_CONTACT_EMAIL';
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';


// USER CONTACTS CONSTANTS
export const USER_CONTACTS_LIST = 'USER_CONTACTS_LIST';

// MESSAGES
export const MESSAGE = 'MESSAGE';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const USER_CHAT_LIST = 'USER_CHAT_LIST';
